### ISSUE TITLE
Unable to change category of character sprites after docker pull

### ISSUE THREAD

**Issue by TheOrionsB** [l3mpire/lemverse#48]
I can't seem to wrap my head around this one.

I have two instances of lemverse set up on two different servers (Instance A and Instance B using the docker-compose-prod example in this repo) and I wasn't able to change the category of character sprites (bought from itch.io) in Instance B, no problems on Instance A.

While trying to figure out what caused the issue, I `docker-compose pull`'ed instance A to get the latest version of lemverse available on docker hub.
I now have the same issue in both instances. A red banner saying "Error while changing category, Match failed"

And this error thrown in the lemverse container:

```updateUsersCharacter: start _FID35 {"from":null,"to":"body","id":"chr_m8yLEPExbvhgr4Mzn","userId":"usr_ZXJgWBoRpyHGjsWXt"}
Exception while invoking method 'updateUsersCharacter' Error: Match error: Expected string, got null in field [0]
    at check (packages/check/match.js:36:17)
    at MethodInvocation.updateUsersCharacter (server/edit-characters.js:10:5)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
    at packages/ddp-server/livedata_server.js:769:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:767:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:765:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:739:23)
    at packages/ddp-server/livedata_server.js:603:43
Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
    at errorClass.<anonymous> (packages/check/match.js:91:27)
    at new errorClass (packages/meteor.js:660:17)
    at check (packages/check/match.js:36:17)
    at MethodInvocation.updateUsersCharacter (server/edit-characters.js:10:5)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
    at packages/ddp-server/livedata_server.js:769:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:767:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:765:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:739:23)
    at packages/ddp-server/livedata_server.js:603:43 {
  isClientSafe: true,
  error: 400,
  reason: 'Match failed',
  details: undefined,
  errorType: 'Meteor.Error'
}
```

Any ideas as to why this happens ?

**Comment by Donorhan** [comment]
Hi! I just committed a patch, sorry about that!
